name: toducate
favicon: null
layout_spectrum: 1
typography_spectrum: 0.61572
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: reflections. musings. aphorisms
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c7d88b'
    - '#4b4a47'
    - '#2b2b2b'
    - '#000000'
    - '#7b8261'
  brandStrength: 0.6875
  lightness: 0.9603668700437993
  saturation: 0
  rhythmicContrast: 1
purpose: []
