analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
layout_spectrum: 0.1733311945572495
cta:
  bucket: null
  version: null
  domain: null
color:
  saturation: 0.8539526963140815
  brandStrength: 0.8547548577189445
  rhythmicContrast: 0.3658582740463316
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  lightness: 0.9603668700437993
purpose: []
favicon: null
name: toducate
typography_spectrum: 0.303499907720834
